### ISSUE TITLE
Research: investigate another Worm repository

### ISSUE THREAD

**Issue by 678098** [Rolandevitt/Test#4]
https://github.com/Rankuli-Ang/Worms

Learn how to read the code from another programmer.

Answer these questions with references to the code:

1. Where is the entry point for the app?
2. What is the current default shape of the world?
3. Is it possible for two or more worms to be inside of one cell?
4. What external library is used for visualization?
5. Do worms mutate only when the child is born?

**Comment by Rolandevitt** [comment]
1. worms.py
2. 100 x 100
3. relative worms could be inside a same cell?
4. cv2
5. functions "insertion_mutation" and "def deletion_mutation" adds/removes 1 random gene?
