### ISSUE TITLE
Remove pycharm project settings files from the repository

### ISSUE THREAD

**Issue by 678098** [Rolandevitt/Test#7]
The folder `.idea` contains PyCharm IDE properties from your local computer. It's not a good style to commit these files to a common code base, because it's not related to the code itself.

- Remove this folder from the repo.
- There is a problem: `git rm -r .idea` will remove the folder from the branch but also it will remove this folder from your disk.

Check `git rm --cached`: https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

**Comment by Rolandevitt** [comment]
done
